using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Windows.Forms;

namespace LiveSplit.JumpKing {
    //get data from enums
    public static class EnumExtensions
    {
        public static string GetDisplayName(this Enum enumValue)
        {
            return enumValue.GetType()
                            .GetMember(enumValue.ToString())
                            .First()
                            .GetCustomAttribute<DisplayAttribute>()
                            .GetName();
        }

    }

    public enum Sections
    {
        //main babe
        [Display(Name = "Redcrown Woods"), Description("Main Babe")] RedcrownWoods,
        [Display(Name = "Colossal Drain"), Description("Main Babe")] ColossalDrain,
        [Display(Name = "False Kings' Keep"), Description("Main Babe")] FalseKingsKeep,
        [Display(Name = "Bargainburg"), Description("Main Babe")] Bargainburg,
        [Display(Name = "Great Frontier"), Description("Main Babe")] GreatFrontier,
        [Display(Name = "Windswept Bluff"), Description("Main Babe")] WindsweptBluff,
        [Display(Name = "Stormwall Pass"), Description("Main Babe")] StormwallPass,
        [Display(Name = "Chapel Perilous"), Description("Main Babe")] ChapelPerilous,
        [Display(Name = "Blue Ruin"), Description("Main Babe")] BlueRuin,
        [Display(Name = "The Tower"), Description("Main Babe")] TheTower,
        [Display(Name = "Main Babe Screen"), Description("Main Babe")] MainBabe,
        [Display(Name = "Unknown"), Description("Main Babe")] Unknown1,

        //new babe+
        [Display(Name = "Room of the Imp"), Description("New Babe Plus")] Bargainburg2,
        [Display(Name = "Brightcrown Woods"), Description("New Babe Plus")] BrightcrownWoods,
        [Display(Name = "Colossal Dungeon"), Description("New Babe Plus")] ColossalDungeon,
        [Display(Name = "False Kings' Castle"), Description("New Babe Plus")] FalseKingsCastle,
        [Display(Name = "Underburg"), Description("New Babe Plus")] Underburg,
        [Display(Name = "Lost Frontier"), Description("New Babe Plus")] LostFrontier,
        [Display(Name = "Hidden Kingdom"), Description("New Babe Plus")] HiddenKingdom,
        [Display(Name = "Black Sanctum"), Description("New Babe Plus")] BlackSanctum,
        [Display(Name = "Deep Ruin"), Description("New Babe Plus")] DeepRuin,
        [Display(Name = "The Dark Tower"), Description("New Babe Plus")] TheDarkTower,
        [Display(Name = "New Babe+ Screen"), Description("New Babe Plus")] NewBabe,
        [Display(Name = "Unknown"), Description("New Babe Plus")] Unknown2,

        //ghost babe
        [Display(Name = "Bog"), Description("Ghost of the Babe")] Bog,
        [Display(Name = "Moulding Manor"), Description("Ghost of the Babe")] MouldingManor,
        [Display(Name = "Bugstalk"), Description("Ghost of the Babe")] Bugstalk,
        [Display(Name = "House Of Nine Lives"), Description("Ghost of the Babe")] HouseOfNineLives,
        [Display(Name = "Phantom Tower"), Description("Ghost of the Babe")] PhantomTower,
        [Display(Name = "Halted Ruin"), Description("Ghost of the Babe")] HaltedRuin,
        [Display(Name = "Tower Of Antumbra"), Description("Ghost of the Babe")] TowerOfAntumbra,
        [Display(Name = "Ghost Babe Screen"), Description("Ghost of the Babe")] GhostBabe,
        [Display(Name = "Unknown"), Description("Ghost of the Babe")] Unknown3,
        [Display(Name = "Philosopher's Forest"), Description("Ghost of the Babe")] PhilosophersForest,
        [Display(Name = "Hole"), Description("Ghost of the Babe")] Hole

    }
    public enum Screen {
        RedcrownWoods1,
        RedcrownWoods2,
        RedcrownWoods3,
        RedcrownWoods4,
        RedcrownWoods5,
        ColossalDrain1,
        ColossalDrain2,
        ColossalDrain3,
        ColossalDrain4,
        ColossalDrain5,
        FalseKingsKeep1,
        FalseKingsKeep2,
        FalseKingsKeep3,
        FalseKingsKeep4,
        Bargainburg1,
        Bargainburg2,
        Bargainburg3,
        Bargainburg4,
        Bargainburg5,
        GreatFrontier1,
        GreatFrontier2,
        GreatFrontier3,
        GreatFrontier4,
        GreatFrontier5,
        GreatFrontier6,
        WindsweptBluff1,
        StormwallPass1,
        StormwallPass2,
        StormwallPass3,
        StormwallPass4,
        StormwallPass5,
        StormwallPass6,
        ChapelPerilous1,
        ChapelPerilous2,
        ChapelPerilous3,
        ChapelPerilous4,
        BlueRuin1,
        BlueRuin2,
        BlueRuin3,
        TheTower1,
        TheTower2,
        TheTower3,
        MainBabe,
        Unknown1,
        Bargainburg6,
        Bargainburg7,
        BrightcrownWoods1,
        BrightcrownWoods2,
        BrightcrownWoods3,
        BrightcrownWoods4,
        BrightcrownWoods5,
        BrightcrownWoods6,
        ColossalDungeon1,
        ColossalDungeon2,
        ColossalDungeon3,
        ColossalDungeon4,
        ColossalDungeon5,
        ColossalDungeon6,
        ColossalDungeon7,
        FalseKingsCastle1,
        FalseKingsCastle2,
        FalseKingsCastle3,
        FalseKingsCastle4,
        Underburg1,
        Underburg2,
        Underburg3,
        Underburg4,
        Underburg5,
        Underburg6,
        Underburg7,
        LostFrontier1,
        LostFrontier2,
        LostFrontier3,
        LostFrontier4,
        LostFrontier5,
        LostFrontier6,
        LostFrontier7,
        HiddenKingdom1,
        HiddenKingdom2,
        HiddenKingdom3,
        HiddenKingdom4,
        HiddenKingdom5,
        HiddenKingdom6,
        BlackSanctum1,
        BlackSanctum2,
        BlackSanctum3,
        BlackSanctum4,
        BlackSanctum5,
        BlackSanctum6,
        DeepRuin1,
        DeepRuin2,
        DeepRuin3,
        DeepRuin4,
        DeepRuin5,
        TheDarkTower1,
        TheDarkTower2,
        TheDarkTower3,
        TheDarkTower4,
        TheDarkTower5,
        NewBabe,
        Unknown2,
        Bog1,
        Bog2,
        Bog3,
        Bog4,
        Bog5,
        Bog6,
        Bog7,
        MouldingManor1,
        MouldingManor2,
        MouldingManor3,
        MouldingManor4,
        MouldingManor5,
        MouldingManor6,
        MouldingManor7,
        MouldingManor8,
        Bugstalk1,
        Bugstalk2,
        Bugstalk3,
        Bugstalk4,
        Bugstalk5,
        Bugstalk6,
        Bugstalk7,
        HouseOfNineLives1,
        HouseOfNineLives2,
        HouseOfNineLives3,
        HouseOfNineLives4,
        HouseOfNineLives5,
        HouseOfNineLives6,
        HouseOfNineLives7,
        PhantomTower1,
        PhantomTower2,
        PhantomTower3,
        PhantomTower4,
        PhantomTower5,
        PhantomTower6,
        PhantomTower7,
        PhantomTower8,
        PhantomTower9,
        HaltedRuin1,
        HaltedRuin2,
        HaltedRuin3,
        HaltedRuin4,
        HaltedRuin5,
        HaltedRuin6,
        HaltedRuin7,
        HaltedRuin8,
        TowerOfAntumbra1,
        TowerOfAntumbra2,
        TowerOfAntumbra3,
        TowerOfAntumbra4,
        TowerOfAntumbra5,
        TowerOfAntumbra6,
        GhostBabe,
        Unknown3,
        PhilosophersForest1,
        PhilosophersForest2,
        PhilosophersForest3,
        PhilosophersForest4,
        PhilosophersForest5,
        Hole4,
        Hole3,
        Hole2,
        Hole1
    }
}